project:
  name: hoqu-geth-api
server:
  host: 0.0.0.0
  port: 8080
  url: http://geth-node.hoqu.io
geth:
  endpoint: https://rinkeby.infura.io
  main:
    key_file: data/keys/main
    pass: key_pass_here
  addr:
    token: 0x1008ba59af5a1efb7db4c10a6d200503785c62f7
    privPlace: 0x020225f157d4e99055356597556d0f6fb06d1184
    presale: 0x124bdbd92e3774b1ef2d3f762a520043bdd0b30a